# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: darwin_amd64
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O3
      - CGO_CXXFLAGS=-O3
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w 
      - -X "main.BuildTags={{.Tag}}"
      - -X "main.BuildTime={{.Date}}"
      - -X "main.GitCommit={{.FullCommit}}"
      - -X "main.GoVersion={{.Env.GOVERSION}} {{.Os}}/{{.Arch}}"

  - id: darwin_arm64
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O3
      - CGO_CXXFLAGS=-O3
      - CC=oa64-clang
      - CXX=oa64-clang++
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w 
      - -X "main.BuildTags={{.Tag}}"
      - -X "main.BuildTime={{.Date}}"
      - -X "main.GitCommit={{.FullCommit}}"
      - -X "main.GoVersion={{.Env.GOVERSION}} {{.Os}}/{{.Arch}}"

  - id: linux_amd64
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O3
      - CGO_CXXFLAGS=-O3
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w 
      - -extldflags '-static'
      - -X "main.BuildTags={{.Tag}}"
      - -X "main.BuildTime={{.Date}}"
      - -X "main.GitCommit={{.FullCommit}}"
      - -X "main.GoVersion={{.Env.GOVERSION}} {{.Os}}/{{.Arch}}"

  - id: linux_arm64
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O3
      - CGO_CXXFLAGS=-O3
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w 
      - -extldflags '-static'
      - -X "main.BuildTags={{.Tag}}"
      - -X "main.BuildTime={{.Date}}"
      - -X "main.GitCommit={{.FullCommit}}"
      - -X "main.GoVersion={{.Env.GOVERSION}} {{.Os}}/{{.Arch}}"

  - id: windows_i686
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O3
      - CGO_CXXFLAGS=-O3
      - CC=i686-w64-mingw32-gcc
      - CXX=i686-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - 386
    ldflags:
      - -s -w 
      - -extldflags '-static'
      - -X "main.BuildTags={{.Tag}}"
      - -X "main.BuildTime={{.Date}}"
      - -X "main.GitCommit={{.FullCommit}}"
      - -X "main.GoVersion={{.Env.GOVERSION}} {{.Os}}/{{.Arch}}"

  - id: windows_amd64
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-O3
      - CGO_CXXFLAGS=-O3
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w 
      - -extldflags '-static'
      - -X "main.BuildTags={{.Tag}}"
      - -X "main.BuildTime={{.Date}}"
      - -X "main.GitCommit={{.FullCommit}}"
      - -X "main.GoVersion={{.Env.GOVERSION}} {{.Os}}/{{.Arch}}"

archives:
  - id: default
    builds:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_i686
      - windows_amd64
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "686" }}i686
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-shapshot"

changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
